version = "0.2"
package = "ca"
license = "GPL"
title = "Cellular Automata"
depends = "terrame (>= 1.5)"
authors = "Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = "Implements the Cellular Automata paradigm."
