version = "0.3"
package = "ca"
license = "GPL"
title = "Cellular Automata"
depends = "terrame (>= 2.0)"
authors = "Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = "Implements the Cellular Automata paradigm."
